dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-rsocket'
    implementation 'org.springframework.boot:spring-boot-starter-web'
}


task jarTests(type: Jar, dependsOn: testClasses) {
    archiveClassifier = 'tests'
    from sourceSets.test.output
}

configurations {
    tests {
        extendsFrom testRuntime
    }
}
artifacts {
    tests jarTests
}

