import groovy.model.ValueHolder

plugins {
    id 'org.springframework.boot' version '2.3.3.RELEASE'
}

def projectSettings = new ValueHolder()
apply from: 'modules.gradle', to: projectSettings


subprojects {
    ext {
        rootProjectInfo = projectSettings.value
        moduleSettings = rootProjectInfo.settings.find { it.name.tokenize(':').last() == name }
    }
    if (moduleSettings != null) {
        group = 'io.segmentme'
        version = moduleSettings.version

        if (moduleSettings.isJava) {
            javaProjectConfiguration(it)

            test {
                useJUnitPlatform()
            }
        }

        if (moduleSettings.isBoot) {
            bootProjectConfiguration(it)
        }
    }
}

def bootProjectConfiguration(Project project) {
    configure(project) {
        apply plugin: 'org.springframework.boot'

    }
}

def javaProjectConfiguration(Project project) {
    configure(project) {
        apply plugin: 'java'
        apply plugin: 'groovy'
        apply plugin: 'io.spring.dependency-management'

        group = 'io.segmentme'
        version = '0.0.1-SNAPSHOT'
        sourceCompatibility = JavaVersion.VERSION_14
        targetCompatibility = JavaVersion.VERSION_14

        configureDependencyManagement(project)
    }
}


def configureDependencyManagement(Project project) {
    configure(project) {

        repositories {
            mavenCentral()
            jcenter()
        }

        wrapper.gradleVersion = '6.6.1'

        dependencies {
            compileOnly 'org.projectlombok:lombok'
            compile 'commons-beanutils:commons-beanutils'

            annotationProcessor 'org.projectlombok:lombok'

            testImplementation('org.springframework.boot:spring-boot-starter-test') {
                exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
            }

            testImplementation "org.spockframework:spock-core"
            testImplementation "org.spockframework:spock-spring"
            testImplementation "cglib:cglib-nodep"
            testImplementation 'org.codehaus.groovy:groovy'
            testCompileOnly 'org.projectlombok:lombok'
            testAnnotationProcessor 'org.projectlombok:lombok'
        }

        dependencyManagement {
            imports {
                mavenBom "org.springframework.boot:spring-boot-dependencies:${rootProjectInfo.springVersion}"
            }

            dependencies {
                dependency 'org.projectlombok:lombok:1.18.12'
                dependency 'org.spockframework:spock-core:2.0-M3-groovy-3.0'
                dependency 'org.spockframework:spock-spring:2.0-M3-groovy-3.0'
                dependency 'cglib:cglib-nodep:3.3.0'
                dependency 'org.codehaus.groovy:groovy:3.0.5'
                dependency 'commons-beanutils:commons-beanutils:1.9.4'
                dependency 'org.apache.commons:commons-lang3:3.11'
            }
        }
    }
}
