io.rsocket.routing.broker:
  broker-id: 00000000-0000-0000-0000-000000000011
  tcp.port: 8002
  cluster.tcp.port: 7002


spring:
  application:
    order: 0
    name: broker-service
  cloud:
    consul:
      discovery:
        instance-group: broker-service
        service-name: broker-service


logging:
  level:
    root: INFO
    io.rsocket.FrameLogger: DEBUG
    io.rsocket: DEBUG

server.port: 8033
