logging:
    level:
        root: ERROR
        io.rsocket.FrameLogger: ERROR
        io.rsocket: DEBUG


io.rsocket.routing.broker:
    broker-id: 00000000-0000-0000-0000-000000000011
    tcp.port: ${BROKER_PORT:8002}
    cluster.tcp.port: ${BROKER_CLUSTER_PORT:7002}


spring:
    application:
        order: 0
        name: broker-service

server.port: 8033
