logging:
    level:
        root: ERROR
        io.segmentme.core.api.resource: INFO
        io.segmentme.core.api.facade.SdkFacade: INFO
        io.segmentme.core.api.config.routing: INFO
        io.rsocket.FrameLogger: ERROR
        io.rsocket: DEBUG

auth0:
    audience: https://segmentme.us.auth0.com/api/v2/
    managementApi: https://segmentme.us.auth0.com/api/v2/
spring:
    application:
        order: 2
        name: analysis-service
    data:
        mongodb:
            auto-index-creation: on
    security:
        oauth2:
            client:
                registration:
                    auth0:
                        client-id: FRFEhM5zwQCva2tSfBxDuM3og5TdjUpC
                        client-secret: Rsic0pW4Wr_q91Ppin-UNRuq5EdH5X7EmhA4ZUTcN-6MBu_Wy8Ce1J89WPCpkD_4
                        authorization-grant-type: client_credentials
                        clientAuthenticationMethod: post
                provider:
                    auth0:
                        token-uri: https://segmentme.us.auth0.com/oauth/token
            resourceserver:
                jwt:
                    issuer-uri: https://segmentme.us.auth0.com/
segmentme:
    rsocket:
        analysisThreadPool:
            corePoolSize: ${ANALYSIS_CORE_POOL_SIZE:10}
            maxPoolSize: ${ANALYSIS_MAX_POOL_SIZE:${segmentme.rsocket.analysisThreadPool.corePoolSize}}
            keepAliveMs: ${ANALYSIS_THREAD_KEEP_ALIVE_MS:0}
        lease:
            capacity: ${LEASE_CAPACITY:100}
            ttl: ${LEASE_TTL_CAPACITY:1000}
            vegasLimit:
                initialLimit: ${LEASE_VEGAS_INIT_LIMIT:${segmentme.rsocket.lease.capacity}}
                maxConcurrency: ${LEASE_VEGAS_MAX_CONCURENCY:5}
    application:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            connectionTimeout: ${REDIS_CONNECTION_TIMEOUT:25}
            readTimeOut: ${REDIS_READ_TIMEOUT:15}
io:
    rsocket:
        routing:
            client:
                #                route-id: 00000000-0000-0000-0000-000000000011
                service-name: analysis-service
                tags:
                    INSTANCE_NAME: analysis-service-1
                brokers:
                    -   tcp:
                            host: ${BROKER_HOST:localhost}
                            port: ${BROKER_PORT:8002}