dependencies {

	compile project(':dependencies:database-dependency')

	compile 'org.springframework.boot:spring-boot-starter-validation'
    compile group: 'commons-codec', name: 'commons-codec', version: '1.15'

	testCompile 'org.springframework.boot:spring-boot-starter-web'
}

task jarTests(type: Jar, dependsOn: testClasses) {
	archiveClassifier = 'tests'
	from sourceSets.test.output
}
configurations {
	tests {
		extendsFrom testRuntime
	}
}

artifacts {
	tests jarTests
}
