dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-rsocket'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compile group: 'redis.clients', name: 'jedis', version: '3.4.1'
    compile project(':dependencies:redis-dependency')

}


task jarTests(type: Jar, dependsOn: testClasses) {
    archiveClassifier = 'tests'
    from sourceSets.test.output
}

configurations {
    tests {
        extendsFrom testRuntime
    }
}
artifacts {
    tests jarTests
}

