
dependencies {
    implementation project(':service')
    implementation project(':database')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation project(path: ':service', configuration: 'tests')
    testImplementation project(path: ':database', configuration: 'tests')
}
